backend:
  name: github
  branch: main
  repo: devsoutinho/mariosouto.com
  base_url: https://mariosouto.com/
  auth_endpoint: api/auth/ # Essa rota vai ser muito importante mais para frente

media_folder: public/images/uploads
public_folder: /images/uploads

publish_mode: editorial_workflow # Isso permite ter aquele workflow com drafts e tudo

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: posts 
    label: posts 
    folder: posts # A pasta onde ficarão os posts
    create: true # Permite criar um post novo
    slug: '{{date}}-{{slug}}' # Estrutura do nome arquivo, exemplo: title.md
    fields: # Os campos do seu frontmatter
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYYMMDD'
        }
      - { label: 'Registered?', name: 'registered', widget: 'boolean', default: false }
      - { label: 'Source', name: 'source', widget: 'hidden', default: 'devsoutinho' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'post' }
      - { label: 'Category', name: "category", widget: "select", options: ["post", "podcast", "event", "video"] }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list',   default: ["javascript"] }
      - { label: 'Body', name: 'body', widget: 'markdown' }